[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"


[project]
name = "kilo-hoku-etl"
version = "0.1.0"
description = "ETL para el procesamiento de datos astronómicos de Kilo Hoku"
requires-python = ">=3.11"

dependencies = [
    "python-dotenv>=1.0.0",
    "pandas>=2.2.0",
    "SQLAlchemy>=2.0.0",
    "psycopg[binary]>=3.2.0",
    "httpx>=0.28.0",
]


[tool.setuptools.packages.find]
where = ["src"]